# Generated by Django 5.2.8 on 2025-11-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=255)),
                ('guest_name', models.CharField(max_length=255)),
                ('overall_rating', models.IntegerField()),
                ('cleanliness_rating', models.IntegerField()),
                ('communication_rating', models.IntegerField()),
                ('respect_house_rules_rating', models.IntegerField()),
                ('public_review', models.TextField()),
                ('submitted_at', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
