# Generated by Django 5.2.8 on 2025-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_category_review_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='channel',
            field=models.CharField(default='Hostaway', max_length=50),
        ),
    ]
